openapi: 3.2.0
info:
  title: Platform Wished Items API
  contact:
    name: Vendo Connect Inc.
    url: https://getvendo.com
    email: sales@getvendo.com
  description: Spree Platform API
  version: v2
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
tags:
- name: Wished Items
paths:
  /api/v2/platform/wished_items:
    get:
      summary: Return a list of Wished Items
      tags:
      - Wished Items
      security:
      - bearer_auth: []
      description: Returns a list of Wished Items
      operationId: wished-items-list
      parameters:
      - name: page
        in: query
        example: 1
        schema:
          type: integer
      - name: per_page
        in: query
        example: 50
        schema:
          type: integer
      - name: include
        in: query
        description: 'Select which associated resources you would like to fetch, see: <a href="https://jsonapi.org/format/#fetching-includes">https://jsonapi.org/format/#fetching-includes</a>'
        example: variant
        schema:
          type: string
      responses:
        '200':
          description: Records returned
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                    - id: '1'
                      type: wished_item
                      attributes:
                        quantity: 1
                        created_at: '2022-11-08T19:36:01.546Z'
                        updated_at: '2022-11-08T19:36:01.546Z'
                        display_total: $19.99
                        display_price: $19.99
                        price: '19.99'
                        total: '19.99'
                      relationships:
                        variant:
                          data:
                            id: '301'
                            type: variant
                    - id: '2'
                      type: wished_item
                      attributes:
                        quantity: 1
                        created_at: '2022-11-08T19:36:01.616Z'
                        updated_at: '2022-11-08T19:36:01.616Z'
                        display_total: $19.99
                        display_price: $19.99
                        price: '19.99'
                        total: '19.99'
                      relationships:
                        variant:
                          data:
                            id: '303'
                            type: variant
                    - id: '3'
                      type: wished_item
                      attributes:
                        quantity: 1
                        created_at: '2022-11-08T19:36:01.685Z'
                        updated_at: '2022-11-08T19:36:01.685Z'
                        display_total: $19.99
                        display_price: $19.99
                        price: '19.99'
                        total: '19.99'
                      relationships:
                        variant:
                          data:
                            id: '305'
                            type: variant
                    - id: '4'
                      type: wished_item
                      attributes:
                        quantity: 1
                        created_at: '2022-11-08T19:36:01.752Z'
                        updated_at: '2022-11-08T19:36:01.752Z'
                        display_total: $19.99
                        display_price: $19.99
                        price: '19.99'
                        total: '19.99'
                      relationships:
                        variant:
                          data:
                            id: '307'
                            type: variant
                    meta:
                      count: 4
                      total_count: 4
                      total_pages: 1
                    links:
                      self: http://www.example.com/api/v2/platform/wished_items?page=1&per_page=&include=
                      next: http://www.example.com/api/v2/platform/wished_items?include=&page=1&per_page=
                      prev: http://www.example.com/api/v2/platform/wished_items?include=&page=1&per_page=
                      last: http://www.example.com/api/v2/platform/wished_items?include=&page=1&per_page=
                      first: http://www.example.com/api/v2/platform/wished_items?include=&page=1&per_page=
              schema:
                $ref: '#/components/schemas/resources_list'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
    post:
      summary: Create a Wished Item
      tags:
      - Wished Items
      security:
      - bearer_auth: []
      description: Creates a Wished Item
      operationId: create-wished-item
      parameters:
      - name: include
        in: query
        description: 'Select which associated resources you would like to fetch, see: <a href="https://jsonapi.org/format/#fetching-includes">https://jsonapi.org/format/#fetching-includes</a>'
        example: variant
        schema:
          type: string
      responses:
        '201':
          description: Record created
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                      id: '9'
                      type: wished_item
                      attributes:
                        quantity: 1
                        created_at: '2022-11-08T19:36:02.710Z'
                        updated_at: '2022-11-08T19:36:02.710Z'
                        display_total: $19.99
                        display_price: $19.99
                        price: '19.99'
                        total: '19.99'
                      relationships:
                        variant:
                          data:
                            id: '319'
                            type: variant
              schema:
                $ref: '#/components/schemas/resource'
        '422':
          description: Invalid request
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: Variant can't be blank, Wishlist can't be blank, and Quantity is not a number
                    errors:
                      variant:
                      - can't be blank
                      wishlist:
                      - can't be blank
                      quantity:
                      - is not a number
              schema:
                $ref: '#/components/schemas/validation_errors'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_wished_item_params'
  /api/v2/platform/wished_items/{id}:
    get:
      summary: Return a Wished Item
      tags:
      - Wished Items
      security:
      - bearer_auth: []
      description: Returns a Wished Item
      operationId: show-wished-item
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: include
        in: query
        description: 'Select which associated resources you would like to fetch, see: <a href="https://jsonapi.org/format/#fetching-includes">https://jsonapi.org/format/#fetching-includes</a>'
        example: variant
        schema:
          type: string
      responses:
        '200':
          description: Record found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                      id: '10'
                      type: wished_item
                      attributes:
                        quantity: 1
                        created_at: '2022-11-08T19:36:03.208Z'
                        updated_at: '2022-11-08T19:36:03.208Z'
                        display_total: $19.99
                        display_price: $19.99
                        price: '19.99'
                        total: '19.99'
                      relationships:
                        variant:
                          data:
                            id: '325'
                            type: variant
              schema:
                $ref: '#/components/schemas/resource'
        '404':
          description: Record not found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The resource you were looking for could not be found.
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
    patch:
      summary: Update a Wished Item
      tags:
      - Wished Items
      security:
      - bearer_auth: []
      description: Updates a Wished Item
      operationId: update-wished-item
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: include
        in: query
        description: 'Select which associated resources you would like to fetch, see: <a href="https://jsonapi.org/format/#fetching-includes">https://jsonapi.org/format/#fetching-includes</a>'
        example: variant
        schema:
          type: string
      responses:
        '200':
          description: Record updated
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                      id: '12'
                      type: wished_item
                      attributes:
                        quantity: 3
                        created_at: '2022-11-08T19:36:04.166Z'
                        updated_at: '2022-11-08T19:36:04.397Z'
                        display_total: $59.97
                        display_price: $19.99
                        price: '19.99'
                        total: '59.97'
                      relationships:
                        variant:
                          data:
                            id: '335'
                            type: variant
              schema:
                $ref: '#/components/schemas/resource'
        '422':
          description: Invalid request
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: Quantity is not a number
                    errors:
                      quantity:
                      - is not a number
              schema:
                $ref: '#/components/schemas/validation_errors'
        '404':
          description: Record not found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The resource you were looking for could not be found.
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_wished_item_params'
    delete:
      summary: Delete a Wished Item
      tags:
      - Wished Items
      security:
      - bearer_auth: []
      description: Deletes a Wished Item
      operationId: delete-wished-item
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Record deleted
        '404':
          description: Record not found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The resource you were looking for could not be found.
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    resource_properties:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
        relationships:
          type: object
      required:
      - id
      - type
      - attributes
      x-internal: false
    create_wished_item_params:
      type: object
      properties:
        wished_item:
          type: object
          required:
          - wishlist_id
          - variant_id
          - quantity
          properties:
            wishlist_id:
              type: string
            variant_id:
              type: string
            quantity:
              type: integer
              description: Must be an integer greater than 0
      required:
      - wished_item
      x-internal: false
    update_wished_item_params:
      type: object
      properties:
        wished_item:
          type: object
          required:
          - wishlist_id
          - variant_id
          - quantity
          properties:
            wishlist_id:
              type: string
            variant_id:
              type: string
            quantity:
              type: integer
              description: Must be an integer greater than 0
      required:
      - wished_item
      x-internal: false
    resources_list:
      type: object
      properties:
        data:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/resource_properties'
        meta:
          type: object
          properties:
            count:
              type: integer
            total_count:
              type: integer
            total_pages:
              type: integer
          required:
          - count
          - total_count
          - total_pages
        links:
          type: object
          properties:
            self:
              type: string
            next:
              type: string
            prev:
              type: string
            last:
              type: string
            first:
              type: string
          required:
          - self
          - next
          - prev
          - last
          - first
      required:
      - data
      - meta
      - links
      x-internal: false
    validation_errors:
      type: object
      properties:
        error:
          type: string
        errors:
          type: object
      required:
      - error
      - errors
      x-internal: false
    resource:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/resource_properties'
      required:
      - data
      x-internal: false
    error:
      type: object
      properties:
        error:
          type: string
      required:
      - error
      x-internal: false
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
