openapi: 3.2.0
info:
  title: Platform Digital Links API
  contact:
    name: Vendo Connect Inc.
    url: https://getvendo.com
    email: sales@getvendo.com
  description: Spree Platform API
  version: v2
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
tags:
- name: Digital Links
paths:
  /api/v2/platform/digital_links:
    get:
      summary: Return a list of Digital Links
      tags:
      - Digital Links
      security:
      - bearer_auth: []
      description: Returns a list of Digital Links
      operationId: digital-links-list
      parameters:
      - name: page
        in: query
        example: 1
        schema:
          type: integer
      - name: per_page
        in: query
        example: 50
        schema:
          type: integer
      responses:
        '200':
          description: Records returned
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                    - id: '1'
                      type: digital_link
                      attributes:
                        token: K5s8uUkdD2TjL8MySKcT3d4Y
                        access_counter: 0
                      relationships:
                        digital:
                          data:
                            id: '1'
                            type: digital
                        line_item:
                          data:
                            id: '9'
                            type: line_item
                    - id: '2'
                      type: digital_link
                      attributes:
                        token: kCrqhTH4d6jUnzGnvx6vRjMH
                        access_counter: 0
                      relationships:
                        digital:
                          data:
                            id: '2'
                            type: digital
                        line_item:
                          data:
                            id: '10'
                            type: line_item
                    meta:
                      count: 2
                      total_count: 2
                      total_pages: 1
                    links:
                      self: http://www.example.com/api/v2/platform/digital_links?page=1&per_page=
                      next: http://www.example.com/api/v2/platform/digital_links?page=1&per_page=
                      prev: http://www.example.com/api/v2/platform/digital_links?page=1&per_page=
                      last: http://www.example.com/api/v2/platform/digital_links?page=1&per_page=
                      first: http://www.example.com/api/v2/platform/digital_links?page=1&per_page=
              schema:
                $ref: '#/components/schemas/resources_list'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
    post:
      summary: Create a Digital Link
      tags:
      - Digital Links
      security:
      - bearer_auth: []
      description: Creates a Digital Link
      operationId: create-digital-link
      parameters: []
      responses:
        '201':
          description: Record created
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                      id: '5'
                      type: digital_link
                      attributes:
                        token: 6bPn1uP9HWaYecdMFkFAkcc3
                        access_counter: 0
                      relationships:
                        digital:
                          data:
                            id: '5'
                            type: digital
                        line_item:
                          data:
                            id: '13'
                            type: line_item
              schema:
                $ref: '#/components/schemas/resource'
        '422':
          description: Invalid request
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: Digital can't be blank, Line item can't be blank, and Access counter is not a number
                    errors:
                      digital:
                      - can't be blank
                      line_item:
                      - can't be blank
                      access_counter:
                      - is not a number
              schema:
                $ref: '#/components/schemas/validation_errors'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_digital_link_params'
  /api/v2/platform/digital_links/{id}:
    get:
      summary: Return a Digital Link
      tags:
      - Digital Links
      security:
      - bearer_auth: []
      description: Returns a Digital Link
      operationId: show-digital-link
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Record found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                      id: '6'
                      type: digital_link
                      attributes:
                        token: vxRU3WSqXJ2J2WbjaC2kLHpg
                        access_counter: 0
                      relationships:
                        digital:
                          data:
                            id: '6'
                            type: digital
                        line_item:
                          data:
                            id: '14'
                            type: line_item
              schema:
                $ref: '#/components/schemas/resource'
        '404':
          description: Record not found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The resource you were looking for could not be found.
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
    patch:
      summary: Update a Digital Link
      tags:
      - Digital Links
      security:
      - bearer_auth: []
      description: Updates a Digital Link
      operationId: update-digital-link
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Record updated
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                      id: '8'
                      type: digital_link
                      attributes:
                        token: hv6VNk8yK2oiZRPsB1pQnazN
                        access_counter: 0
                      relationships:
                        digital:
                          data:
                            id: '8'
                            type: digital
                        line_item:
                          data:
                            id: '16'
                            type: line_item
              schema:
                $ref: '#/components/schemas/resource'
        '422':
          description: Invalid request
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: Access counter is not a number
                    errors:
                      access_counter:
                      - is not a number
              schema:
                $ref: '#/components/schemas/validation_errors'
        '404':
          description: Record not found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The resource you were looking for could not be found.
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_digital_link_params'
    delete:
      summary: Delete a Digital Link
      tags:
      - Digital Links
      security:
      - bearer_auth: []
      description: Deletes a Digital Link
      operationId: delete-digital-link
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Record deleted
        '404':
          description: Record not found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The resource you were looking for could not be found.
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
  /api/v2/platform/digital_links/{id}/reset:
    patch:
      summary: Reset a Digital Link
      tags:
      - Digital Links
      security:
      - bearer_auth: []
      operationId: reset-digital-link
      description: Resets a digital link, allowing further downloads.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Record updated
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                      id: '13'
                      type: digital_link
                      attributes:
                        token: NBDYF1WRkrnFJewp4PqjATdQ
                        access_counter: 0
                      relationships:
                        digital:
                          data:
                            id: '13'
                            type: digital
                        line_item:
                          data:
                            id: '21'
                            type: line_item
              schema:
                $ref: '#/components/schemas/resource'
        '404':
          description: Record not found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The resource you were looking for could not be found.
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    resource_properties:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
        relationships:
          type: object
      required:
      - id
      - type
      - attributes
      x-internal: false
    update_digital_link_params:
      type: object
      properties:
        digital_link:
          type: object
          properties:
            access_counter:
              type: integer
              example: 0
            line_item_id:
              type: string
              example: '1'
            digital_id:
              type: string
              example: '1'
      required:
      - digital_link
      x-internal: false
    create_digital_link_params:
      type: object
      properties:
        digital_link:
          type: object
          required:
          - line_item_id
          - digital_id
          properties:
            access_counter:
              type: integer
              example: 0
            line_item_id:
              type: string
              example: '1'
            digital_id:
              type: string
              example: '1'
      required:
      - digital_link
      x-internal: false
    resources_list:
      type: object
      properties:
        data:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/resource_properties'
        meta:
          type: object
          properties:
            count:
              type: integer
            total_count:
              type: integer
            total_pages:
              type: integer
          required:
          - count
          - total_count
          - total_pages
        links:
          type: object
          properties:
            self:
              type: string
            next:
              type: string
            prev:
              type: string
            last:
              type: string
            first:
              type: string
          required:
          - self
          - next
          - prev
          - last
          - first
      required:
      - data
      - meta
      - links
      x-internal: false
    validation_errors:
      type: object
      properties:
        error:
          type: string
        errors:
          type: object
      required:
      - error
      - errors
      x-internal: false
    resource:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/resource_properties'
      required:
      - data
      x-internal: false
    error:
      type: object
      properties:
        error:
          type: string
      required:
      - error
      x-internal: false
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
