openapi: 3.2.0
info:
  title: Platform Promotion Rules API
  contact:
    name: Vendo Connect Inc.
    url: https://getvendo.com
    email: sales@getvendo.com
  description: Spree Platform API
  version: v2
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
tags:
- name: Promotion Rules
paths:
  /api/v2/platform/promotion_rules:
    get:
      summary: Return a list of Promotion Rules
      tags:
      - Promotion Rules
      security:
      - bearer_auth: []
      description: Returns a list of Promotion Rules
      operationId: promotion-rules-list
      parameters:
      - name: page
        in: query
        example: 1
        schema:
          type: integer
      - name: per_page
        in: query
        example: 50
        schema:
          type: integer
      - name: include
        in: query
        description: 'Select which associated resources you would like to fetch, see: <a href="https://jsonapi.org/format/#fetching-includes">https://jsonapi.org/format/#fetching-includes</a>'
        example: user
        schema:
          type: string
      - name: filter[type_eq]
        in: query
        description: ''
        example: Spree::Promotion::Rules::Product
        schema:
          type: string
      responses:
        '200':
          description: Records returned
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                    - id: '1'
                      type: promotion_rule
                      attributes:
                        type: null
                        created_at: '2022-11-08T19:35:00.589Z'
                        updated_at: '2022-11-08T19:35:00.589Z'
                        code: null
                        preferences: {}
                      relationships:
                        promotion:
                          data:
                            id: '14'
                            type: promotion
                    - id: '2'
                      type: promotion_rule
                      attributes:
                        type: null
                        created_at: '2022-11-08T19:35:00.591Z'
                        updated_at: '2022-11-08T19:35:00.591Z'
                        code: null
                        preferences: {}
                      relationships:
                        promotion:
                          data:
                            id: '14'
                            type: promotion
                    meta:
                      count: 2
                      total_count: 2
                      total_pages: 1
                    links:
                      self: http://www.example.com/api/v2/platform/promotion_rules?page=1&per_page=&include=&filter[type_eq]=
                      next: http://www.example.com/api/v2/platform/promotion_rules?filter%5Btype_eq%5D=&include=&page=1&per_page=
                      prev: http://www.example.com/api/v2/platform/promotion_rules?filter%5Btype_eq%5D=&include=&page=1&per_page=
                      last: http://www.example.com/api/v2/platform/promotion_rules?filter%5Btype_eq%5D=&include=&page=1&per_page=
                      first: http://www.example.com/api/v2/platform/promotion_rules?filter%5Btype_eq%5D=&include=&page=1&per_page=
              schema:
                $ref: '#/components/schemas/resources_list'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
    post:
      summary: Create a Promotion Rule
      tags:
      - Promotion Rules
      security:
      - bearer_auth: []
      description: Creates a Promotion Rule
      operationId: create-promotion-rule
      parameters:
      - name: include
        in: query
        description: 'Select which associated resources you would like to fetch, see: <a href="https://jsonapi.org/format/#fetching-includes">https://jsonapi.org/format/#fetching-includes</a>'
        example: user
        schema:
          type: string
      responses:
        '201':
          description: Record created
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                      id: '5'
                      type: promotion_rule
                      attributes:
                        type: null
                        created_at: '2022-11-08T19:35:01.131Z'
                        updated_at: '2022-11-08T19:35:01.131Z'
                        code: null
                        preferences: {}
                      relationships:
                        promotion:
                          data:
                            id: '16'
                            type: promotion
              schema:
                $ref: '#/components/schemas/resource'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_promotion_rule_params'
  /api/v2/platform/promotion_rules/{id}:
    get:
      summary: Return a Promotion Rule
      tags:
      - Promotion Rules
      security:
      - bearer_auth: []
      description: Returns a Promotion Rule
      operationId: show-promotion-rule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: include
        in: query
        description: 'Select which associated resources you would like to fetch, see: <a href="https://jsonapi.org/format/#fetching-includes">https://jsonapi.org/format/#fetching-includes</a>'
        example: user
        schema:
          type: string
      responses:
        '200':
          description: Record found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                      id: '6'
                      type: promotion_rule
                      attributes:
                        type: null
                        created_at: '2022-11-08T19:35:01.163Z'
                        updated_at: '2022-11-08T19:35:01.163Z'
                        code: null
                        preferences: {}
                      relationships:
                        promotion:
                          data:
                            id: '17'
                            type: promotion
              schema:
                $ref: '#/components/schemas/resource'
        '404':
          description: Record not found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The resource you were looking for could not be found.
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
    patch:
      summary: Update a Promotion Rule
      tags:
      - Promotion Rules
      security:
      - bearer_auth: []
      description: Updates a Promotion Rule
      operationId: update-promotion-rule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: include
        in: query
        description: 'Select which associated resources you would like to fetch, see: <a href="https://jsonapi.org/format/#fetching-includes">https://jsonapi.org/format/#fetching-includes</a>'
        example: user
        schema:
          type: string
      responses:
        '200':
          description: Record updated
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                      id: '8'
                      type: promotion_rule
                      attributes:
                        type: Spree::Promotion::Rules::Country
                        created_at: '2022-11-08T19:35:01.723Z'
                        updated_at: '2022-11-08T19:35:01.953Z'
                        code: null
                        preferences: {}
                      relationships:
                        promotion:
                          data:
                            id: '19'
                            type: promotion
              schema:
                $ref: '#/components/schemas/resource'
        '404':
          description: Record not found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The resource you were looking for could not be found.
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_promotion_rule_params'
    delete:
      summary: Delete a Promotion Rule
      tags:
      - Promotion Rules
      security:
      - bearer_auth: []
      description: Deletes a Promotion Rule
      operationId: delete-promotion-rule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Record deleted
        '404':
          description: Record not found
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The resource you were looking for could not be found.
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    create_promotion_rule_params:
      type: object
      properties:
        promotion_rule:
          type: object
          required:
          - type
          - promotion_id
          properties:
            promotion_id:
              type: string
              example: '22'
              description: Set the ID of the promotion this Promotion Rule belongs to.
            type:
              type: string
              example: Spree::Promotion::Rules::Country
              enum:
              - Spree::Promotion::Rules::Country
              - Spree::Promotion::Rules::ItemTotal
              - Spree::Promotion::Rules::Product
              - Spree::Promotion::Rules::User
              - Spree::Promotion::Rules::FirstOrder
              - Spree::Promotion::Rules::UserLoggedIn
              - Spree::Promotion::Rules::OneUsePerUser
              - Spree::Promotion::Rules::Taxon
              - Spree::Promotion::Rules::OptionValue
              description: Set the Promotion Rule type.
      required:
      - promotion_rule
      title: Create a Promotion Rule
      x-internal: false
    resource_properties:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
        relationships:
          type: object
      required:
      - id
      - type
      - attributes
      x-internal: false
    resources_list:
      type: object
      properties:
        data:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/resource_properties'
        meta:
          type: object
          properties:
            count:
              type: integer
            total_count:
              type: integer
            total_pages:
              type: integer
          required:
          - count
          - total_count
          - total_pages
        links:
          type: object
          properties:
            self:
              type: string
            next:
              type: string
            prev:
              type: string
            last:
              type: string
            first:
              type: string
          required:
          - self
          - next
          - prev
          - last
          - first
      required:
      - data
      - meta
      - links
      x-internal: false
    update_promotion_rule_params:
      type: object
      properties:
        promotion_rule:
          type: object
          properties:
            type:
              type: string
              example: Spree::Promotion::Rules::Country
              enum:
              - Spree::Promotion::Rules::Country
              - Spree::Promotion::Rules::ItemTotal
              - Spree::Promotion::Rules::Product
              - Spree::Promotion::Rules::User
              - Spree::Promotion::Rules::FirstOrder
              - Spree::Promotion::Rules::UserLoggedIn
              - Spree::Promotion::Rules::OneUsePerUser
              - Spree::Promotion::Rules::Taxon
              - Spree::Promotion::Rules::OptionValue
              description: Set the Promotion Rule type.
      required:
      - promotion_rule
      title: Create a Promotion Rule
      x-internal: false
    resource:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/resource_properties'
      required:
      - data
      x-internal: false
    error:
      type: object
      properties:
        error:
          type: string
      required:
      - error
      x-internal: false
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
