openapi: 3.2.0
info:
  title: Platform Webhook Events API
  contact:
    name: Vendo Connect Inc.
    url: https://getvendo.com
    email: sales@getvendo.com
  description: Spree Platform API
  version: v2
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
tags:
- name: Webhook Events
paths:
  /api/v2/platform/webhooks/events:
    get:
      summary: Return a list of Webhook Events
      tags:
      - Webhook Events
      security:
      - bearer_auth: []
      description: Returns a list of Webhook Events
      operationId: webhook-events-list
      parameters:
      - name: page
        in: query
        example: 1
        schema:
          type: integer
      - name: per_page
        in: query
        example: 50
        schema:
          type: integer
      - name: include
        in: query
        description: 'Select which associated resources you would like to fetch, see: <a href="https://jsonapi.org/format/#fetching-includes">https://jsonapi.org/format/#fetching-includes</a>'
        example: subscriber
        schema:
          type: string
      - name: filter[name_eq]
        in: query
        description: ''
        example: order.canceled
        schema:
          type: string
      - name: filter[request_errors_cont]
        in: query
        description: ''
        example: google
        schema:
          type: string
      - name: filter[response_code_eq]
        in: query
        description: ''
        example: '200'
        schema:
          type: string
      - name: filter[success_eq]
        in: query
        description: ''
        example: 'true'
        schema:
          type: string
      - name: filter[url_cont]
        in: query
        description: ''
        example: mysite
        schema:
          type: string
      responses:
        '200':
          description: Records returned
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    data:
                    - id: '1'
                      type: event
                      attributes:
                        execution_time: 14933
                        name: order.canceled
                        request_errors: ''
                        response_code: '200'
                        success: true
                        url: https://www.url1.com/
                        created_at: '2022-11-08T19:35:58.544Z'
                        updated_at: '2022-11-08T19:35:58.544Z'
                      relationships:
                        subscriber:
                          data:
                            id: '1'
                            type: subscriber
                    - id: '2'
                      type: event
                      attributes:
                        execution_time: 64917
                        name: order.canceled
                        request_errors: ''
                        response_code: '200'
                        success: true
                        url: https://www.url2.com/
                        created_at: '2022-11-08T19:35:58.547Z'
                        updated_at: '2022-11-08T19:35:58.547Z'
                      relationships:
                        subscriber:
                          data:
                            id: '2'
                            type: subscriber
                    meta:
                      count: 2
                      total_count: 2
                      total_pages: 1
                    links:
                      self: http://www.example.com/api/v2/platform/webhooks/events?page=1&per_page=&include=&filter[name_eq]=&filter[request_errors_cont]=&filter[response_code_eq]=&filter[success_eq]=&filter[url_cont]=
                      next: http://www.example.com/api/v2/platform/webhooks/events?filter%5Bname_eq%5D=&filter%5Brequest_errors_cont%5D=&filter%5Bresponse_code_eq%5D=&filter%5Bsuccess_eq%5D=&filter%5Burl_cont%5D=&include=&page=1&per_page=
                      prev: http://www.example.com/api/v2/platform/webhooks/events?filter%5Bname_eq%5D=&filter%5Brequest_errors_cont%5D=&filter%5Bresponse_code_eq%5D=&filter%5Bsuccess_eq%5D=&filter%5Burl_cont%5D=&include=&page=1&per_page=
                      last: http://www.example.com/api/v2/platform/webhooks/events?filter%5Bname_eq%5D=&filter%5Brequest_errors_cont%5D=&filter%5Bresponse_code_eq%5D=&filter%5Bsuccess_eq%5D=&filter%5Burl_cont%5D=&include=&page=1&per_page=
                      first: http://www.example.com/api/v2/platform/webhooks/events?filter%5Bname_eq%5D=&filter%5Brequest_errors_cont%5D=&filter%5Bresponse_code_eq%5D=&filter%5Bsuccess_eq%5D=&filter%5Burl_cont%5D=&include=&page=1&per_page=
              schema:
                $ref: '#/components/schemas/resources_list'
        '401':
          description: Authentication Failed
          content:
            application/vnd.api+json:
              examples:
                Example:
                  value:
                    error: The access token is invalid
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    resource_properties:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
        relationships:
          type: object
      required:
      - id
      - type
      - attributes
      x-internal: false
    error:
      type: object
      properties:
        error:
          type: string
      required:
      - error
      x-internal: false
    resources_list:
      type: object
      properties:
        data:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/resource_properties'
        meta:
          type: object
          properties:
            count:
              type: integer
            total_count:
              type: integer
            total_pages:
              type: integer
          required:
          - count
          - total_count
          - total_pages
        links:
          type: object
          properties:
            self:
              type: string
            next:
              type: string
            prev:
              type: string
            last:
              type: string
            first:
              type: string
          required:
          - self
          - next
          - prev
          - last
          - first
      required:
      - data
      - meta
      - links
      x-internal: false
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
